[package]
name = "the_shadow_of_the_west"
version = "0.1.0"
authors = ["ciuciek123","Sara Ryfczynska","rafmuss","Wyvar Toldram","Kajteq","kondiiq"]
edition = "2018"

[dependencies.amethyst]
version = "0.12.0"
features = ["vulkan"]
